version: '3.1'

services:
  db:
    ports:
      - "5431:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: java
      POSTGRES_DB: test
      POSTGRES_USER: java
